from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from huggingface_hub import InferenceClient
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI()

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ Create the client
client = InferenceClient(
    model="google/flan-t5-small",
    token=os.getenv("HUGGINGFACEHUB_API_TOKEN")
)

class TripRequest(BaseModel):
    destination: str
    days: int
    interests: str

@app.post("/plan-trip")
def plan_trip(req: TripRequest):
    prompt = f"""You are a helpful travel assistant.
Plan a {req.days}-day trip to {req.destination} based on these interests: {req.interests}.
Return a short, friendly summary of the itinerary with key activities, food, and culture."""

    try:
        print(f"📨 Prompt:\n{prompt}\n")
        output = client.text_generation(prompt, max_new_tokens=300, temperature=0.7)
        print(f"✅ Output:\n{output}\n")

        return {
            "destination": req.destination,
            "days": req.days,
            "interests": req.interests.split(","),
            "message": output
        }

    except StopIteration:
        return {"message": "StopIteration error: No response generated by the model."}
    except Exception as e:
        return {"message": f"Sorry, something went wrong: {repr(e)}"}

@app.get("/")
def read_root():
    return {"message": "Travel Companion AI Backend is running!"}
